#! genpac __VERSION__ https://github.com/JinnLynn/genpac
[RULESET.gfwed]
name = "GFWed rules"
rules = [
__GFWED_RULES__
]

[RULESET.direct]
name = "Direct rules"
rules = [
__DIRECT_RULES__
]
#! Generated: __GENERATED__
#! GFWList: __MODIFIED__ From __GFWLIST_FROM__
